// <auto-generated />
namespace To_Gather.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UserActivityChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserActivityChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "202104122036327_UserActivityChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
